title: Joshua Wiegmann
description: > # this means to ignore newlines until "baseurl:"
  from Hannover with ❤️
permalink: ':title/'
baseurl: ""
url: "https://joshuaw.de" 
site-twitter: joxw1

# Author Settings
author: Joshua Wiegmann # add your name
author-img: joshua-wiegmann.png # add your photo
about-author: Hi! Ich bin Joshua, Softwareentwickler aus Hannover und ich versuche ein Code Ninja zu werden 🏃‍♂
social-twitter: joxw1 # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: joxw1 # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: joshua.wiegmann@pm.me # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: UA-176843375-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
